docs_dir: doc/book/ru
pages:
    - index.md
    - 'Интеграционные модули':
      - 'Концепция интеграционных модулей': 'integration-module.md'
      - 'Конфигурирование модулей сервиса': 'configure-service-module.md'
site_name: module
site_description: 'Набор решений и у утилит, для упрощения работы с модулями zf2'
repo_url: 'https://github.com/nnx-framework/module'
copyright: 'Copyright (c) 2016 <a href="https://github.com/nnx-framework">NNX</a>'
